language: cpp

sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode7.2

    - os: osx
      osx_image: xcode7.3

before_install:
  - brew update
  - brew tap nlohmann/json

script:
  - uname -a
  - which $CXX
  - $CXX --version
  - brew audit nlohmann_json
  - brew install nlohmann_json
  - brew test nlohmann_json
