sudo: false
language: cpp
matrix:
  include:
    - osx_image: xcode7.2
    - osx_image: xcode7.3
before_install:
  - brew update
  - brew tap nlohmann/json
script:
  - uname -a
  - which $CXX
  - $CXX --version
  - brew audit nlohmann_json
  - brew install nlohmann_json
  - brew test nlohmann_json
